#Requires -Version 5.1
<#
.SYNOPSIS
    Synchronizuje agentní konfiguraci vrstev z src/<Layer>/.cursor/ do root .cursor/.

.DESCRIPTION
    Každá vrstva vlastní svou agentní konfiguraci v src/<Layer>/.cursor/. Cursor ale
    vnořené .cursor složky načítá nespolehlivě, proto tento skript vytváří zrcadlo
    v root .cursor/:

      src/<Layer>/.cursor/rules/*.mdc      -> .cursor/rules/generated/<slug>/*.mdc
      src/<Layer>/.cursor/agents/*.md      -> .cursor/agents/<slug>-*.md
      src/<Layer>/.cursor/skills/<x>/...   -> .cursor/skills/<slug>-<x>/...

    Pravidlům se přepíše globs na ["src/<Layer>/**"] a přidá se hlavička GENERATED.
    Generované soubory jsou evidovány v .cursor/.generated-manifest.json, aby bylo
    možné spolehlivě odstranit osiřelé soubory.

    Skript zapisuje výhradně do root .cursor/ a jen u souborů vedených v manifestu.
    Zdroje v src/<Layer>/.cursor/ nikdy nemění.

.PARAMETER Check
    Nic nezapisuje. Selže (exit 1), pokud je root konfigurace zastaralá, chybí
    nebo existují osiřelé generované soubory. Používá CI.

.EXAMPLE
    pwsh -File scripts/sync-agent-config.ps1
    pwsh -File scripts/sync-agent-config.ps1 -Check
#>
[CmdletBinding()]
param(
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'lib/i18n.ps1')

$scriptDir = $PSScriptRoot
$root = Split-Path -Parent $scriptDir
$srcRoot = Join-Path $root 'src'
$cursorRoot = Join-Path $root '.cursor'
$manifestPath = Join-Path $cursorRoot '.generated-manifest.json'
$marker = 'GENERATED by scripts/sync-agent-config.ps1 - do not edit'

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

# ---------------------------------------------------------------------------
# Pomocné funkce
# ---------------------------------------------------------------------------

function Get-LayerSlug {
    param([string]$Value)

    $step1 = [regex]::Replace($Value, '([a-z0-9])([A-Z])', '$1-$2')
    $step2 = [regex]::Replace($step1, '([A-Z]+)([A-Z][a-z])', '$1-$2')
    return $step2.ToLowerInvariant()
}

function Read-TextFile {
    param([string]$Path)
    return [System.IO.File]::ReadAllText($Path)
}

function Convert-ToLf {
    param([string]$Text)
    return ($Text -replace "`r`n", "`n")
}

function Get-FrontmatterValue {
    param([string]$Text, [string]$Field)

    if ($Text -notmatch '(?s)^---\s*\r?\n(.*?)\r?\n---') { return $null }

    $frontmatter = $Matches[1]
    if ($frontmatter -match "(?m)^\s*$([regex]::Escape($Field))\s*:\s*(.+?)\s*$") {
        return $Matches[1].Trim().Trim('"').Trim("'")
    }

    return $null
}

function Get-MarkdownBody {
    param([string]$Text)

    if ($Text -match '(?s)^---\s*\r?\n.*?\r?\n---\s*\r?\n?') {
        return $Text.Substring($Matches[0].Length)
    }

    return $Text
}

function Convert-ToYamlSafe {
    param([string]$Value)
    return ($Value -replace '"', "'").Trim()
}

function New-GeneratedFile {
    param([string]$RelativePath, [string]$Content)
    $script:expected[$RelativePath] = (Convert-ToLf $Content)
}

function Write-Utf8File {
    param([string]$Path, [string]$Content)

    $dir = Split-Path -Parent $Path
    if ($dir -and -not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }

    [System.IO.File]::WriteAllText($Path, (Convert-ToLf $Content), $utf8NoBom)
}

function Get-LayerDirectories {
    if (-not (Test-Path -LiteralPath $srcRoot)) { return @() }

    return @(Get-ChildItem -LiteralPath $srcRoot -Directory | Where-Object {
        $_.Name -match '^[A-Z][A-Za-z0-9]*$' -and
        (Test-Path -LiteralPath (Join-Path $_.FullName '.cursor'))
    } | Sort-Object Name)
}

# ---------------------------------------------------------------------------
# Sestavení očekávaného stavu
# ---------------------------------------------------------------------------

$expected = @{}
$layers = Get-LayerDirectories

foreach ($layerItem in $layers) {
    $layer = $layerItem.Name
    $slug = Get-LayerSlug -Value $layer
    $cursorDir = Join-Path $layerItem.FullName '.cursor'

    # --- rules: <Layer>/.cursor/rules/*.mdc -> .cursor/rules/generated/<slug>/ ---
    $rulesDir = Join-Path $cursorDir 'rules'
    if (Test-Path -LiteralPath $rulesDir) {
        foreach ($ruleFile in @(Get-ChildItem -LiteralPath $rulesDir -Filter '*.mdc' -File)) {
            $text = Read-TextFile $ruleFile.FullName
            $description = Get-FrontmatterValue -Text $text -Field 'description'
            if ([string]::IsNullOrWhiteSpace($description)) { $description = "$layer standards" }
            $description = Convert-ToYamlSafe $description

            $body = (Convert-ToLf (Get-MarkdownBody $text)).Trim()

            $content = "---`n" +
                       "description: `"[$layer] $description`"`n" +
                       "globs: [`"src/$layer/**`"]`n" +
                       "alwaysApply: false`n" +
                       "---`n" +
                       "<!-- $marker | source: src/$layer/.cursor/rules/$($ruleFile.Name) -->`n`n" +
                       $body + "`n"

            New-GeneratedFile -RelativePath ".cursor/rules/generated/$slug/$($ruleFile.Name)" -Content $content
        }
    }

    # --- agents: <Layer>/.cursor/agents/*.md -> .cursor/agents/<slug>-*.md ---
    $agentsDir = Join-Path $cursorDir 'agents'
    if (Test-Path -LiteralPath $agentsDir) {
        foreach ($agentFile in @(Get-ChildItem -LiteralPath $agentsDir -Filter '*.md' -File)) {
            $text = Read-TextFile $agentFile.FullName

            $name = Get-FrontmatterValue -Text $text -Field 'name'
            if ([string]::IsNullOrWhiteSpace($name)) { $name = [System.IO.Path]::GetFileNameWithoutExtension($agentFile.Name) }

            $description = Get-FrontmatterValue -Text $text -Field 'description'
            if ([string]::IsNullOrWhiteSpace($description)) { $description = "$layer agent" }

            $model = Get-FrontmatterValue -Text $text -Field 'model'
            if ([string]::IsNullOrWhiteSpace($model)) { $model = 'inherit' }

            $readonly = Get-FrontmatterValue -Text $text -Field 'readonly'
            if ([string]::IsNullOrWhiteSpace($readonly)) { $readonly = 'false' }

            $isBackground = Get-FrontmatterValue -Text $text -Field 'is_background'
            if ([string]::IsNullOrWhiteSpace($isBackground)) { $isBackground = 'false' }

            $body = (Convert-ToLf (Get-MarkdownBody $text)).Trim()

            # Zdroj může být už prefixovaný slugem vrstvy — pak ho neprefixuj znovu.
            $resolvedName = $name
            if (-not ($name -eq $slug -or $name.StartsWith("$slug-"))) {
                $resolvedName = "$slug-$name"
            }

            $content = "---`n" +
                       "name: $resolvedName`n" +
                       "description: `"[$layer] $(Convert-ToYamlSafe $description)`"`n" +
                       "model: $model`n" +
                       "readonly: $readonly`n" +
                       "is_background: $isBackground`n" +
                       "---`n`n" +
                       $body + "`n"

            New-GeneratedFile -RelativePath ".cursor/agents/$slug-$($agentFile.Name)" -Content $content
        }
    }

    # --- skills: <Layer>/.cursor/skills/<x>/** -> .cursor/skills/<slug>-<x>/** ---
    $skillsDir = Join-Path $cursorDir 'skills'
    if (Test-Path -LiteralPath $skillsDir) {
        foreach ($skillDir in @(Get-ChildItem -LiteralPath $skillsDir -Directory)) {
            $targetSkill = "$slug-$($skillDir.Name)"

            foreach ($file in @(Get-ChildItem -LiteralPath $skillDir.FullName -Recurse -File)) {
                $relativeInside = $file.FullName.Substring($skillDir.FullName.Length).TrimStart('\', '/')
                $targetRelative = ".cursor/skills/$targetSkill/$($relativeInside -replace '\\', '/')"

                if ($file.Name -eq 'SKILL.md') {
                    $text = Read-TextFile $file.FullName

                    $name = Get-FrontmatterValue -Text $text -Field 'name'
                    if ([string]::IsNullOrWhiteSpace($name)) { $name = $skillDir.Name }

                    $description = Get-FrontmatterValue -Text $text -Field 'description'
                    if ([string]::IsNullOrWhiteSpace($description)) { $description = "$layer skill" }

                    $body = (Convert-ToLf (Get-MarkdownBody $text)).Trim()

                    $resolvedName = $name
                    if (-not ($name -eq $slug -or $name.StartsWith("$slug-"))) {
                        $resolvedName = "$slug-$name"
                    }

                    $content = "---`n" +
                               "name: $resolvedName`n" +
                               "description: `"[$layer] $(Convert-ToYamlSafe $description)`"`n" +
                               "disable-model-invocation: true`n" +
                               "---`n`n" +
                               $body + "`n"

                    New-GeneratedFile -RelativePath $targetRelative -Content $content
                }
                else {
                    New-GeneratedFile -RelativePath $targetRelative -Content (Read-TextFile $file.FullName)
                }
            }
        }
    }
}

# ---------------------------------------------------------------------------
# Porovnání se skutečným stavem
# ---------------------------------------------------------------------------

$previous = @()
if (Test-Path -LiteralPath $manifestPath) {
    try {
        $previous = @((Read-TextFile $manifestPath | ConvertFrom-Json) | Where-Object { $_ -is [string] })
    }
    catch {
        $previous = @()
    }
}

$changed = New-Object System.Collections.Generic.List[string]
$missing = New-Object System.Collections.Generic.List[string]

foreach ($relative in ($expected.Keys | Sort-Object)) {
    $full = Join-Path $root ($relative -replace '/', '\')

    if (-not (Test-Path -LiteralPath $full)) {
        $missing.Add($relative)
        continue
    }

    $actual = Convert-ToLf (Read-TextFile $full)
    if ($actual -ne $expected[$relative]) {
        $changed.Add($relative)
    }
}

$orphans = New-Object System.Collections.Generic.List[string]
foreach ($relative in $previous) {
    if (-not $expected.ContainsKey($relative)) {
        $orphans.Add($relative)
    }
}

# ---------------------------------------------------------------------------
# Režim -Check
# ---------------------------------------------------------------------------

if ($Check) {
    $problems = @()

    if ($missing.Count -gt 0) {
        $problems += Get-Text 'sync.missing' @{ count = $missing.Count }
        $problems += ($missing | ForEach-Object { "  - $_" })
    }

    if ($changed.Count -gt 0) {
        $problems += Get-Text 'sync.stale' @{ count = $changed.Count }
        $problems += ($changed | ForEach-Object { "  - $_" })
    }

    if ($orphans.Count -gt 0) {
        $problems += Get-Text 'sync.orphans' @{ count = $orphans.Count }
        $problems += ($orphans | ForEach-Object { "  - $_" })
    }

    if ($problems.Count -gt 0) {
        Write-Host (Get-Text 'sync.notInSync') -ForegroundColor Red
        Write-Host ""
        $problems | ForEach-Object { Write-Host $_ }
        Write-Host ""
        Write-Host (Get-Text 'sync.runHint' @{ cmd = 'pwsh -File scripts/sync-agent-config.ps1' }) -ForegroundColor Yellow
        exit 1
    }

    Write-Host (Get-Text 'sync.ok' @{ count = $expected.Count }) -ForegroundColor Green
    exit 0
}

# ---------------------------------------------------------------------------
# Zápis
# ---------------------------------------------------------------------------

foreach ($relative in $changed) {
    Write-Host "  update $relative"
}

foreach ($relative in $missing) {
    Write-Host "  create $relative"
}

# Zapisuj pouze to, co se skutečně změnilo — sync je tak idempotentní
# a nezpůsobuje zbytečné změny mtime (a tím pádem falešné "modified" v gitu).
foreach ($relative in (@($changed) + @($missing))) {
    $full = Join-Path $root ($relative -replace '/', '\')
    Write-Utf8File -Path $full -Content $expected[$relative]
}

foreach ($relative in $orphans) {
    $full = Join-Path $root ($relative -replace '/', '\')
    if (Test-Path -LiteralPath $full) {
        Remove-Item -LiteralPath $full -Force
        Write-Host "  remove $relative"
    }
}

# Úklid prázdných adresářů po osiřelých souborech (jen generované oblasti).
foreach ($base in @((Join-Path $cursorRoot 'rules/generated'), (Join-Path $cursorRoot 'skills'))) {
    if (-not (Test-Path -LiteralPath $base)) { continue }

    $dirs = @(Get-ChildItem -LiteralPath $base -Directory -Recurse -Force |
        Sort-Object -Property { $_.FullName.Length } -Descending)

    foreach ($dir in $dirs) {
        $files = @(Get-ChildItem -LiteralPath $dir.FullName -Recurse -File -Force)
        if ($files.Count -eq 0 -and -not (Test-Path -LiteralPath (Join-Path $dir.FullName '.keep'))) {
            Remove-Item -LiteralPath $dir.FullName -Recurse -Force
            Write-Host (Get-Text 'sync.emptyDir' @{ name = $dir.Name })
        }
    }
}

$manifestKeys = @($expected.Keys | Sort-Object)
$manifestContent = (ConvertTo-Json -InputObject ([string[]]$manifestKeys) -Depth 3) + "`n"

$existingManifest = $null
if (Test-Path -LiteralPath $manifestPath) {
    $existingManifest = Convert-ToLf (Read-TextFile $manifestPath)
}

if ($existingManifest -ne (Convert-ToLf $manifestContent)) {
    Write-Utf8File -Path $manifestPath -Content $manifestContent
}

Write-Host ""
Write-Host (Get-Text 'sync.done' @{ layers = $layers.Count; files = $expected.Count }) -ForegroundColor Green
Write-Host (Get-Text 'sync.sourceNote') -ForegroundColor DarkGray
