#Requires -Version 5.1
<#
.SYNOPSIS
    Synchronizuje agentní konfiguraci vrstev z src/<vrstva>/.cursor/ do root .cursor/.

.DESCRIPTION
    Každá vrstva vlastní svou agentní konfiguraci v src/<vrstva>/.cursor/. Cursor ale
    vnořené .cursor složky v monorepu načítá nespolehlivě, proto tento skript vytváří
    zrcadlo v root .cursor/:

      src/<vrstva>/.cursor/rules/*.mdc        -> .cursor/rules/generated/<vrstva>/*.mdc
      src/<vrstva>/.cursor/agents/*.md        -> .cursor/agents/<vrstva>-*.md
      src/<vrstva>/.cursor/skills/<x>/...     -> .cursor/skills/<vrstva>-<x>/...

    Pravidlům se přepíše globs na ["src/<vrstva>/**"] a přidá se hlavička GENERATED.
    Generované soubory jsou evidovány v .cursor/.generated-manifest.json, aby bylo
    možné spolehlivě odstranit osiřelé soubory.

.PARAMETER Check
    Nic nezapisuje. Selže (exit 1), pokud je root konfigurace zastaralá, chybí
    nebo existují osiřelé generované soubory. Používá CI.

.EXAMPLE
    pwsh -File scripts/sync-agent-config.ps1
    pwsh -File scripts/sync-agent-config.ps1 -Check
#>
[CmdletBinding()]
param(
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$scriptDir = $PSScriptRoot
$root = Split-Path -Parent $scriptDir
$srcRoot = Join-Path $root 'src'
$cursorRoot = Join-Path $root '.cursor'
$manifestPath = Join-Path $cursorRoot '.generated-manifest.json'
$marker = 'GENERATED by scripts/sync-agent-config.ps1 - do not edit'

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

# ---------------------------------------------------------------------------
# Pomocné funkce
# ---------------------------------------------------------------------------

function Read-TextFile {
    param([string]$Path)
    return [System.IO.File]::ReadAllText($Path)
}

function Convert-ToLf {
    param([string]$Text)
    return ($Text -replace "`r`n", "`n")
}

function Get-FrontmatterValue {
    param([string]$Text, [string]$Field)

    if ($Text -notmatch '(?s)^---\s*\r?\n(.*?)\r?\n---') { return $null }

    $frontmatter = $Matches[1]
    if ($frontmatter -match "(?m)^\s*$([regex]::Escape($Field))\s*:\s*(.+?)\s*$") {
        return $Matches[1].Trim().Trim('"').Trim("'")
    }

    return $null
}

function Get-MarkdownBody {
    param([string]$Text)

    if ($Text -match '(?s)^---\s*\r?\n.*?\r?\n---\s*\r?\n?') {
        return $Text.Substring($Matches[0].Length)
    }

    return $Text
}

function Convert-ToYamlSafe {
    param([string]$Value)
    return ($Value -replace '"', "'").Trim()
}

function New-GeneratedFile {
    param([string]$RelativePath, [string]$Content)
    $script:expected[$RelativePath] = (Convert-ToLf $Content)
}

function Write-Utf8File {
    param([string]$Path, [string]$Content)

    $dir = Split-Path -Parent $Path
    if ($dir -and -not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }

    # Vždy zapisuj LF, aby byl výstup na Windows a Linuxu bajtově shodný
    # (ConvertTo-Json na Windows produkuje CRLF).
    [System.IO.File]::WriteAllText($Path, (Convert-ToLf $Content), $utf8NoBom)
}

function Get-LayerDirectories {
    if (-not (Test-Path -LiteralPath $srcRoot)) { return @() }

    return @(Get-ChildItem -LiteralPath $srcRoot -Directory | Where-Object {
        Test-Path -LiteralPath (Join-Path $_.FullName '.cursor')
    } | Sort-Object Name)
}

# ---------------------------------------------------------------------------
# Sestavení očekávaného stavu
# ---------------------------------------------------------------------------

$expected = @{}
$layers = Get-LayerDirectories

foreach ($layerItem in $layers) {
    $layer = $layerItem.Name
    $cursorDir = Join-Path $layerItem.FullName '.cursor'

    # --- rules: <vrstva>/.cursor/rules/*.mdc -> .cursor/rules/generated/<vrstva>/ ---
    $rulesDir = Join-Path $cursorDir 'rules'
    if (Test-Path -LiteralPath $rulesDir) {
        foreach ($ruleFile in @(Get-ChildItem -LiteralPath $rulesDir -Filter '*.mdc' -File)) {
            $text = Read-TextFile $ruleFile.FullName
            $description = Get-FrontmatterValue -Text $text -Field 'description'
            if ([string]::IsNullOrWhiteSpace($description)) { $description = "$layer standards" }
            $description = Convert-ToYamlSafe $description

            $body = Convert-ToLf (Get-MarkdownBody $text)
            $body = $body.Trim()

            $content = "---`n" +
                       "description: `"[$layer] $description`"`n" +
                       "globs: [`"src/$layer/**`"]`n" +
                       "alwaysApply: false`n" +
                       "---`n" +
                       "<!-- $marker | source: src/$layer/.cursor/rules/$($ruleFile.Name) -->`n`n" +
                       $body + "`n"

            New-GeneratedFile -RelativePath ".cursor/rules/generated/$layer/$($ruleFile.Name)" -Content $content
        }
    }

    # --- agents: <vrstva>/.cursor/agents/*.md -> .cursor/agents/<vrstva>-*.md ---
    $agentsDir = Join-Path $cursorDir 'agents'
    if (Test-Path -LiteralPath $agentsDir) {
        foreach ($agentFile in @(Get-ChildItem -LiteralPath $agentsDir -Filter '*.md' -File)) {
            $text = Read-TextFile $agentFile.FullName

            $name = Get-FrontmatterValue -Text $text -Field 'name'
            if ([string]::IsNullOrWhiteSpace($name)) { $name = [System.IO.Path]::GetFileNameWithoutExtension($agentFile.Name) }

            $description = Get-FrontmatterValue -Text $text -Field 'description'
            if ([string]::IsNullOrWhiteSpace($description)) { $description = "$layer agent" }

            $model = Get-FrontmatterValue -Text $text -Field 'model'
            if ([string]::IsNullOrWhiteSpace($model)) { $model = 'inherit' }

            $readonly = Get-FrontmatterValue -Text $text -Field 'readonly'
            if ([string]::IsNullOrWhiteSpace($readonly)) { $readonly = 'false' }

            $isBackground = Get-FrontmatterValue -Text $text -Field 'is_background'
            if ([string]::IsNullOrWhiteSpace($isBackground)) { $isBackground = 'false' }

            $body = (Convert-ToLf (Get-MarkdownBody $text)).Trim()

            # Zdroj už může být prefixovaný názvem vrstvy (např. "domain-dev") —
            # v tom případě ho neprefixuj znovu.
            $resolvedName = $name
            if (-not ($name -eq $layer -or $name.StartsWith("$layer-"))) {
                $resolvedName = "$layer-$name"
            }

            $content = "---`n" +
                       "name: $resolvedName`n" +
                       "description: `"[$layer] $(Convert-ToYamlSafe $description)`"`n" +
                       "model: $model`n" +
                       "readonly: $readonly`n" +
                       "is_background: $isBackground`n" +
                       "---`n`n" +
                       $body + "`n"

            New-GeneratedFile -RelativePath ".cursor/agents/$layer-$($agentFile.Name)" -Content $content
        }
    }

    # --- skills: <vrstva>/.cursor/skills/<x>/** -> .cursor/skills/<vrstva>-<x>/** ---
    $skillsDir = Join-Path $cursorDir 'skills'
    if (Test-Path -LiteralPath $skillsDir) {
        foreach ($skillDir in @(Get-ChildItem -LiteralPath $skillsDir -Directory)) {
            $targetSkill = "$layer-$($skillDir.Name)"

            foreach ($file in @(Get-ChildItem -LiteralPath $skillDir.FullName -Recurse -File)) {
                $relativeInside = $file.FullName.Substring($skillDir.FullName.Length).TrimStart('\', '/')
                $targetRelative = ".cursor/skills/$targetSkill/$($relativeInside -replace '\\', '/')"

                if ($file.Name -eq 'SKILL.md') {
                    $text = Read-TextFile $file.FullName

                    $name = Get-FrontmatterValue -Text $text -Field 'name'
                    if ([string]::IsNullOrWhiteSpace($name)) { $name = $skillDir.Name }

                    $description = Get-FrontmatterValue -Text $text -Field 'description'
                    if ([string]::IsNullOrWhiteSpace($description)) { $description = "$layer skill" }

                    $body = (Convert-ToLf (Get-MarkdownBody $text)).Trim()

                    $resolvedName = $name
                    if (-not ($name -eq $layer -or $name.StartsWith("$layer-"))) {
                        $resolvedName = "$layer-$name"
                    }

                    $content = "---`n" +
                               "name: $resolvedName`n" +
                               "description: `"[$layer] $(Convert-ToYamlSafe $description)`"`n" +
                               "disable-model-invocation: true`n" +
                               "---`n`n" +
                               $body + "`n"

                    New-GeneratedFile -RelativePath $targetRelative -Content $content
                }
                else {
                    New-GeneratedFile -RelativePath $targetRelative -Content (Read-TextFile $file.FullName)
                }
            }
        }
    }
}

# ---------------------------------------------------------------------------
# Porovnání se skutečným stavem
# ---------------------------------------------------------------------------

$previous = @()
if (Test-Path -LiteralPath $manifestPath) {
    try {
        $previous = @((Read-TextFile $manifestPath | ConvertFrom-Json) | Where-Object { $_ -is [string] })
    }
    catch {
        $previous = @()
    }
}

$changed = New-Object System.Collections.Generic.List[string]
$missing = New-Object System.Collections.Generic.List[string]

foreach ($relative in ($expected.Keys | Sort-Object)) {
    $full = Join-Path $root ($relative -replace '/', '\')

    if (-not (Test-Path -LiteralPath $full)) {
        $missing.Add($relative)
        continue
    }

    $actual = Convert-ToLf (Read-TextFile $full)
    if ($actual -ne $expected[$relative]) {
        $changed.Add($relative)
    }
}

$orphans = New-Object System.Collections.Generic.List[string]
foreach ($relative in $previous) {
    if (-not $expected.ContainsKey($relative)) {
        $orphans.Add($relative)
    }
}

# ---------------------------------------------------------------------------
# Režim -Check
# ---------------------------------------------------------------------------

if ($Check) {
    $problems = @()

    if ($missing.Count -gt 0) {
        $problems += "Chybějící generované soubory ($($missing.Count)):"
        $problems += ($missing | ForEach-Object { "  - $_" })
    }

    if ($changed.Count -gt 0) {
        $problems += "Zastaralé generované soubory ($($changed.Count)):"
        $problems += ($changed | ForEach-Object { "  - $_" })
    }

    if ($orphans.Count -gt 0) {
        $problems += "Osiřelé generované soubory ($($orphans.Count)):"
        $problems += ($orphans | ForEach-Object { "  - $_" })
    }

    if ($problems.Count -gt 0) {
        Write-Host "Agentní konfigurace NENÍ v souladu se zdroji ve vrstvách." -ForegroundColor Red
        Write-Host ""
        $problems | ForEach-Object { Write-Host $_ }
        Write-Host ""
        Write-Host "Spusť: pwsh -File scripts/sync-agent-config.ps1" -ForegroundColor Yellow
        exit 1
    }

    Write-Host "Agentní konfigurace je v souladu ($($expected.Count) generovaných souborů)." -ForegroundColor Green
    exit 0
}

# ---------------------------------------------------------------------------
# Zápis
# ---------------------------------------------------------------------------

foreach ($relative in $changed) {
    Write-Host "  update $relative"
}

foreach ($relative in $missing) {
    Write-Host "  create $relative"
}

foreach ($relative in $expected.Keys) {
    $full = Join-Path $root ($relative -replace '/', '\')
    Write-Utf8File -Path $full -Content $expected[$relative]
}

foreach ($relative in $orphans) {
    $full = Join-Path $root ($relative -replace '/', '\')
    if (Test-Path -LiteralPath $full) {
        Remove-Item -LiteralPath $full -Force
        Write-Host "  remove $relative"
    }
}

# Úklid prázdných adresářů po osiřelých souborech (rules/generated i skills)
foreach ($base in @((Join-Path $cursorRoot 'rules/generated'), (Join-Path $cursorRoot 'skills'))) {
    if (-not (Test-Path -LiteralPath $base)) { continue }

    # Od nejhlubších adresářů, aby se uklidily i vnořené prázdné složky.
    $dirs = @(Get-ChildItem -LiteralPath $base -Directory -Recurse -Force |
        Sort-Object -Property { $_.FullName.Length } -Descending)

    foreach ($dir in $dirs) {
        if (@(Get-ChildItem -LiteralPath $dir.FullName -Recurse -File -Force).Count -eq 0) {
            Remove-Item -LiteralPath $dir.FullName -Recurse -Force
            Write-Host "  remove $($dir.Name)/ (prázdný)"
        }
    }
}

$manifestKeys = @($expected.Keys | Sort-Object)
$manifestJson = ConvertTo-Json -InputObject ([string[]]$manifestKeys) -Depth 3
Write-Utf8File -Path $manifestPath -Content ($manifestJson + "`n")

Write-Host ""
Write-Host "Synchronizace dokončena: $($layers.Count) vrstev, $($expected.Count) generovaných souborů." -ForegroundColor Green
Write-Host "Zdroj pravdy: src/<vrstva>/.cursor/ | Generováno: .cursor/ (needitovat)" -ForegroundColor DarkGray
